Importing libraries

In [2]:
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
import torch

Broadcasting in tensorflow

In [3]:
a = tf.constant([4,5,6])
b = tf.constant(2)
c = tf.constant([3, 3, 3])

print(tf.multiply(a, 2))
print(a * b)
print(a * c)

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([12 15 18], shape=(3,), dtype=int32)


In [4]:
a = tf.constant([2,4,6,7])
b = tf.constant([1,2,3,4])
print(tf.add(a,b)) 


tf.Tensor([ 3  6  9 11], shape=(4,), dtype=int32)


String tensors using tensorflow

In [8]:
aa = tf.constant("CMPE 258")
print(aa)

tf.Tensor(b'CMPE 258', shape=(), dtype=string)


In [9]:
bb = tf.constant(["CMPE 258","Deep Learning","Artificial Intelligence"])

print(bb)

tf.Tensor([b'CMPE 258' b'Deep Learning' b'Artificial Intelligence'], shape=(3,), dtype=string)


In [10]:
print(tf.strings.split(aa, sep=" "))

tf.Tensor([b'CMPE' b'258'], shape=(2,), dtype=string)


In [11]:
print(tf.strings.split(bb))

<tf.RaggedTensor [[b'CMPE', b'258'],
 [b'Deep', b'Learning'],
 [b'Artificial', b'Intelligence']]>


Sparse Tensors using tensorflow

In [12]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


Ragged Tensors using tensorflow

In [13]:
l = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [14]:
ragged_tensor = tf.ragged.constant(l)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [15]:
ragged_tensor.shape

TensorShape([4, None])

Broadcasting using torch

In [19]:
x = torch.tensor([4,5,6])
y = torch.tensor(2)
z = torch.tensor([3, 3, 3])
 

print(torch.mul(x, 2))
print(x * y)
print(x * z)

tensor([ 8, 10, 12])
tensor([ 8, 10, 12])
tensor([12, 15, 18])


In [20]:
a = torch.tensor([2,4,6,7])
b = torch.tensor([1,2,3,4])
print(torch.add(a,b)) 

tensor([ 3,  6,  9, 11])


String Tensors using torch

In [21]:
string = "CMPE 258"
ascii_codes = [ord(c) for c in string]
print(torch.tensor(ascii_codes))

tensor([67, 77, 80, 69, 32, 50, 53, 56])


In [23]:
s = torch.tensor(3)

v = "5"
n = int(v)

st = torch.tensor(n)
print(st)

tensor(5)


Sparse Tensor using torch

In [24]:
indices = torch.tensor([[0, 1], [1, 2], [2, 0]])
values = torch.tensor([1, 2, 3])

sparse_tensor = torch.sparse_coo_tensor(indices.t(), values, size=(3, 3))

print(sparse_tensor)

print(sparse_tensor[1, 2])

tensor(indices=tensor([[0, 1, 2],
                       [1, 2, 0]]),
       values=tensor([1, 2, 3]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
tensor(2)


Ragged Tensor using torch

In [25]:
a, b = torch.arange(3), torch.arange(5) + 3
nt = torch.nested.nested_tensor([a, b])
print("a: ", a)
print("b: ", b)
print("nested tensor: ", nt)

a:  tensor([0, 1, 2])
b:  tensor([3, 4, 5, 6, 7])
nested tensor:  nested_tensor([
  tensor([0, 1, 2]),
  tensor([3, 4, 5, 6, 7])
])


/usr/local/lib/python3.9/dist-packages/torch/nested/__init__.py:47: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
  nt = torch._nested_tensor_from_tensor_list(new_data, dtype, None, device, pin_memory)


In [26]:
nt.dim()

2

Named Tensor using Pytorch

In [16]:
torch.zeros(2, 3, names=('N', 'C'))

<ipython-input-16-eb74a8e0f1fd>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  torch.zeros(2, 3, names=('N', 'C'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

In [17]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
imgs.names

('N', 'C', 'H', 'W')

In [18]:
renamed_imgs = imgs.rename(H='height', W='width')
renamed_imgs.names

('N', 'C', 'height', 'width')

Linear search

In [27]:
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

arr = tf.constant([59, 78, 86, 102, 230, 231, 675, 892])
target = tf.constant(102)

result = linear_search(arr, target)
print(result)

3


Insertion sort


In [28]:
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr = tf.tensor_scatter_nd_update(arr, [[j+1]], [arr[j]])
            j = j - 1
        arr = tf.tensor_scatter_nd_update(arr, [[j+1]], [key])
    return arr

arr = tf.constant([3, 5, 2, 6, 8, 1])
result = insertion_sort(arr)
print(result)

tf.Tensor([1 2 3 5 6 8], shape=(6,), dtype=int32)


Binary search

In [30]:
def binary_search(arr, target):
    low = 0
    high = len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

arr = tf.constant([1, 2, 3, 4, 5])
target = tf.constant(4)

result = linear_search(arr, target)
print(result)

3
